### ISSUE TITLE
documentation of tests outdated?

### ISSUE THREAD

**Issue by grst** [theislab/diffxpy#120]
The documentation of `test.wald` states

> * formula_loc – formula model formula for location and scale parameter models. If not specified, formula will be used instead.
> * formula_scale – formula model formula for scale parameter model. If not specified, formula will be used instead.

The documentation of `test.lrt` states: 

> * full_formula_loc – formula Full model formula for location parameter model. If not specified, full_formula will be used instead.
> * reduced_formula_loc – formula Reduced model formula for location and scale parameter models. If not specified, reduced_formula will be used instead.
> * full_formula_scale – formula Full model formula for scale parameter model. If not specified, reduced_formula_scale will be used instead.
> * reduced_formula_scale – formula Reduced model formula for scale parameter model. If not specified, reduced_formula will be used instead.

`formula` or `full_formula` and `reduced_formula` respectively don't seem to be supported parameters any more and as far as I can tell from the code `loc` and `scale` formulas have now to be specified explicitly.

**Comment by davidsebfischer** [comment]
Thanks for the pointer @grst! Both are indeed depreceated, I removed these sentences from the documenation!
