### ISSUE TITLE
install error?

### ISSUE THREAD

**Issue by jipeifeng** [theislab/diffxpy#121]
Hi,
   After installing diffxpy using pip, I only got de.enable_logging(), de.log_cfg, de.logger, de.unconfiguer_logging(). No test() command was observed.

**Comment by jipeifeng** [comment]
By the way, I also installed this tool following the tutorials, but still got the same problem. I can import the package using: import diffxpy as de, but got the error:
>>> test = de.test.t_test(
...     data=X,
...     grouping="condition",
...     sample_description=sample_description
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'diffxpy' has no attribute 'test'

**Comment by davidsebfischer** [comment]
Hi @jipeifeng! Thanks for the issue and sorry for the long wait. You have to import diffxpy like this: `import diffxpy.api as de`. That should resolve your issue!
