### ISSUE TITLE
Bulk RNAseq

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/diffxpy#150]
Can diffxpy be used to analysis differential expression of bulk RNAseq data? just like edgeR and DESeq2.

**Comment by davidsebfischer** [comment]
Hi @wangjiawen2013! Yes, you can do that! Notice though that we do not have empirical Bayes on dispersion estiamtes implemented, so you might overfits dispersion, DESeq2 is nice in that case! We are working on empirical Bayes but it is not very high up the list as it is not standardly used in single-cell, where you have many more observations.
