### ISSUE TITLE
wilcoxon exception all numbers are the same

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/diffxpy#40]
Scipy throws an error in this case, this should be caught by the wrapper in the daughter of DifferentialExpressionTestSingle.

`/opt/conda/lib/python3.6/site-packages/diffxpy/testing/base.py in pairwise(data, grouping, test, gene_names, sample_description, noise_model, pval_correction, batch_size, training_strategy, keep_full_test_objs, **kwargs)
   1632                     batch_size=batch_size,
   1633                     training_strategy=training_strategy,
-> 1634                     **kwargs
   1635                 )
   1636                 pvals[i, j] = de_test_temp.pval

/opt/conda/lib/python3.6/site-packages/diffxpy/testing/base.py in two_sample(data, grouping, test, gene_names, sample_description, noise_model, batch_size, training_strategy, **kwargs)
   1461             data=X,
   1462             gene_names=gene_names,
-> 1463             grouping=grouping,
   1464         )
   1465     else:

/opt/conda/lib/python3.6/site-packages/diffxpy/testing/base.py in wilcoxon(data, grouping, gene_names, sample_description)
   1311         data=data,
   1312         grouping=grouping,
-> 1313         gene_ids=gene_names,
   1314     )
   1315 

/opt/conda/lib/python3.6/site-packages/diffxpy/testing/base.py in __init__(self, data, grouping, gene_ids)
    607         x0, x1 = _split_X(data, grouping)
    608 
--> 609         self._pval = stats.wilcoxon_test(x0=x0.data, x1=x1.data)
    610         self._logfc = np.log(np.mean(x1, axis=0)) - np.log(np.mean(x0, axis=0)).data
    611         q = self.qval

/opt/conda/lib/python3.6/site-packages/diffxpy/stats/stats.py in wilcoxon_test(x0, x1)
     69             y=x1[:, i].flatten(),
     70             alternative='two-sided'
---> 71         ).pvalue for i in range(x0.shape[1])
     72     ])
     73     return pvals

/opt/conda/lib/python3.6/site-packages/diffxpy/stats/stats.py in <listcomp>(.0)
     69             y=x1[:, i].flatten(),
     70             alternative='two-sided'
---> 71         ).pvalue for i in range(x0.shape[1])
     72     ])
     73     return pvals

/opt/conda/lib/python3.6/site-packages/scipy/stats/stats.py in mannwhitneyu(x, y, use_continuity, alternative)
   4895     T = tiecorrect(ranked)
   4896     if T == 0:
-> 4897         raise ValueError('All numbers are identical in mannwhitneyu')
   4898     sd = np.sqrt(T * n1 * n2 * (n1+n2+1) / 12.0)
   4899 

ValueError: All numbers are identical in mannwhitneyu`

**Comment by aopisco** [comment]
any progress fixing this?

**Comment by davidsebfischer** [comment]
Genes with zero variance groups caused this and are now filtered and handled separately.
