### ISSUE TITLE
release 0.4

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/diffxpy#65]
Merge dev into master and do release 0.4 once all public release issues are done.

**Comment by Hoeze** [comment]
Release v0.4.x is ready. Only the docs are missing

**Comment by davidsebfischer** [comment]
Done in https://github.com/theislab/diffxpy/commit/990d7923321c12422361a873604767d7a14beb8e. Release 0.4.2 in https://github.com/theislab/diffxpy/releases/tag/v0.4.2.
