### ISSUE TITLE
ttest clipping

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/diffxpy#67]
I tried really hard to get the clipping here to work, for some reason it just does not work and keeps throwing warnings for zero dev.:
https://github.com/theislab/diffxpy/blob/fb319f74ff69d18ca19cdff609ebe882b42ba838/diffxpy/stats/stats.py#L158
@Hoeze, can you also have a look at it? I ll send you some example data.

**Comment by Hoeze** [comment]
Should be fixed in 5ac2ee4d58674fe8e0b7058d215d16a47c37ae52
