### ISSUE TITLE
diffxpy.api.enrich.test throws error when used with gene_ids and pval input

### ISSUE THREAD

**Issue by ld2113** [theislab/diffxpy#83]
I just tried to run an enrichment analysis using diffxpy 0.4.2. I do not use a DE Test object as input to the enrichment test, but manually specify the `gene_ids` and `pval` arguments.

This produces the following error:

```Python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-33921779303b> in <module>
----> 1 test = de.enrich.test(RefSets=rs_curated, pval=de_allmerged_fdr[0], gene_ids=np.array(de_allmerged_genes[0]).tolist(), de_threshold=0.05)

~/anaconda3/envs/orgacute/lib/python3.6/site-packages/diffxpy/enrichment/enrich.py in test(RefSets, DETest, pval, gene_ids, de_threshold, all_ids, clean_ref, upper)
    234         all_ids=all_ids,
    235         clean_ref=clean_ref,
--> 236         upper=upper)
    237 
    238 

~/anaconda3/envs/orgacute/lib/python3.6/site-packages/diffxpy/enrichment/enrich.py in __init__(self, RefSets, DETest, pval, gene_ids, de_threshold, all_ids, clean_ref, upper)
    275 
    276         self._significant_de = self._qval_de <= de_threshold
--> 277         self._significant_ids = set(self._gene_ids[np.where(self._significant_de)[0]])
    278         if all_ids is not None:
    279             self._all_ids = set(all_ids)

TypeError: only integer scalar arrays can be converted to a scalar index
```

I am pretty sure, that python lists such as self._gene_ids here: https://github.com/theislab/diffxpy/blob/7e47156e77f69c76942642cabdbffa5b32ea3bb0/diffxpy/enrichment/enrich.py#L277 do not support boolean indexing with numpy arrays. When `gene_ids` is passed as a numpy array (instead of a list as specified) the error disappears.

**Comment by davidsebfischer** [comment]
Thanks @ld2113, looks as if you identified and fixed the issue correctly, I will try to add it into dev by end of this week!

**Comment by davidsebfischer** [comment]
Fixed in https://github.com/theislab/diffxpy/commit/74203fc90c9290f51a02330760bafabab8b752d9.

**Comment by ld2113** [comment]
I think this might need to be reopened. I am still running into issues here. The new behaviour is that no matter whether `gene_ids` is passed as a list or numpy array an error gets thrown.

This is because the nupy array now automatically gets converted to a list here: https://github.com/theislab/diffxpy/blob/8f1a0a0518f2f0c0153d9d519d5f8327e8fabbd4/diffxpy/enrichment/enrich.py#L267

As lists can not be indexed by boolean arrays, this line now always produces an error regardless of the `gene_ids` input type:
https://github.com/theislab/diffxpy/blob/8f1a0a0518f2f0c0153d9d519d5f8327e8fabbd4/diffxpy/enrichment/enrich.py#L296

**Comment by davidsebfischer** [comment]
Should be fixed in https://github.com/theislab/diffxpy/commit/82d64860a5fd2aaef4b6d066220a65cb4cb7502e, I switched to nd.arrays throughour and added a lot of unit tests around this so I hope that there is no setting in which such errors still occur. Just re-open again if it does!
