### ISSUE TITLE
diffxpy.api.enrich.Enrich api is not compatible with current structure of DEtest.summary()

### ISSUE THREAD

**Issue by ld2113** [theislab/diffxpy#85]
I am currently using diffxpy installed from the dev branch last week. I am attempting to run an enrichment analysis on a `DifferentialExpressionTestWald` object. It seems like the output of `DifferentialExpressionTestWald.summary()` has changed as the column `zero_mean` does not exist in there anymore. As diffxpy.api.enrich.Enrich is still expecting this column, it fails with an error here: https://github.com/theislab/diffxpy/blob/4c8a7ab796ba66e508c4015e9370f4564edb08c0/diffxpy/enrichment/enrich.py#L273

**Comment by davidsebfischer** [comment]
Thanks for the issue, @ld2113! Fixed here on dev: https://github.com/theislab/diffxpy/commit/058ec3786332e3a259c8bdc740026856637719ac.
